Vagrant.configure("2") do |config|
  config.vm.provider "vmware_fusion"
  config.vm.box = "ekai-upt/macos-catalina"

	# Allow mapping the salt folder
  config.vm.synced_folder "salt/", "/srv/salt/", type: "nfs"
  config.vm.network "private_network", ip: "192.168.33.33"

	# Provision with salt masterless
	config.vm.provision :salt do |salt|
	  salt.masterless = true
	  salt.run_highstate = true
	  salt.colorize = true
	  salt.verbose = true
	  salt.log_level = "debug"
	end
end